### ISSUE TITLE
RobotWalk Scanner

### ISSUE THREAD

**Issue by KimJinsu66** [KimJinsu66/TeamProject-2#1]
RobtWalk에서 스캐너를 반복적으로 진행할지
RobotWalk 밖에서 ArrayList를 통해 보낼지 고민해야 할 것 같습니다!

**Comment by KimJinsu66** [comment]
1. int speed에서 1.2를 곱하게 되면 speed가 float or double이 되는대 이 문제에 대해서는 어떻게 해야할지 고민해봐야됩니다.
2. 최고 속도에 대해서도 기준점이 필요할 것 같습니다 !

**Comment by yuikateraoka** [comment]
처음에는 로봇이  다른 곳에서 명랑을 받고 인식해서 움직이는게 아니라 스스로 인식해서 행동하는 인공지능인 것 같다고 생각했는데 사양서를 잘 보면 교통신호의 상태에 따라서 로봇의 보행속도를 결정한다고 써 있기 때문에 스스로가 아니라 다른 곳에서 명랑을 받고 행동할 가능성도 생각했습니다. 로봇이 보행속도를 결정한다고 써 있으면 "RobtWalk에서 스캐너를 반복적으로 진행"하는 것이 좋을 것 같지만, 좀 다시 같이 고민할 필요가 있다고 생각합니다.

**Comment by yuikateraoka** [comment]
1.int speed에서 1.2를 곱하게 되면 speed가 float or double이 되는대 이 문제에 대해서는 어떻게 해야할지 고민해봐야됩니다.
>> 원래 RobotWalk를 double로 선언하면 어떨까 싶습니다.

2.최고 속도에 대해서도 기준점이 필요할 것 같습니다 !
>>일단 그 로봇이 2족 보행인지 4족 보행인지 사양서를 봐도 모르겠지만,
Boston Dynamics가 개발한 최신 몬스터 'Wild Cat' 같은 로봇은 군용 4족 보행으로 최고 시속 16마일(약 26km)로 주행할 수 있습니다. 이 로봇은 2013년 때 나온 세계 최고 속도의 로봇이라고 합니다. 근데 2020년 현재에서의 자료를 찾아도 세계 최고로 나오니까 최고 속도는 26km로 정하는게 어떻습니까?

**Comment by KimJinsu66** [comment]
감사합니다. 최고 속도에 대해 관련해서는 수요일에 교수님에게 질문하자고 정했습니다. Windows 10용 메일에서 보냄 보낸 사람: yuikateraoka보낸 날짜: 2020년 4월 6일 월요일 오전 11:01받는 사람: KimJinsu66/TeamProject-2참조: KimJinsu66; Author제목: Re: [KimJinsu66/TeamProject-2] RobotWalk Scanner (#1) 1.int speed에서 1.2를 곱하게 되면 speed가 float or double이 되는대 이 문제에 대해서는 어떻게 해야할지 고민해봐야됩니다.원래 RobotWalk를 double로 선언하면 어떨까 싶습니다.2.최고 속도에 대해서도 기준점이 필요할 것 같습니다 !일단 그 로봇이 2족 보행인지 4족 보행인지 사양서를 봐도 모르겠지만,Boston Dynamics가 개발한 최신 몬스터 'Wild Cat' 같은 로봇은 군용 4족 보행으로 최고 시속 16마일(약 26km)로 주행할 수 있습니다. 이 로봇은 2013년 때 나온 세계 최고 속도의 로봇이라고 합니다. 근데 2020년 현재에서의 자료를 찾아도 세계 최고로 나오니까 최고 속도는 26km로 정하는게 어떻습니까?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by KimJinsu66** [comment]
맞는 말이네요 다시한번 고민해보겠습니다.Speed의 경우 ArrayList로 해서 외부에서 보내고 있고 Speed1의 경우 내부에서 판단하고 있습니다.이것도 질문할 필요가 있다고 생각합니다.Windows 10용 메일에서 보냄 보낸 사람: yuikateraoka보낸 날짜: 2020년 4월 6일 월요일 오전 10:44받는 사람: KimJinsu66/TeamProject-2참조: KimJinsu66; Author제목: Re: [KimJinsu66/TeamProject-2] RobotWalk Scanner (#1) 처음에는 로봇이 다른 곳에서 명랑을 받고 인식해서 움직이는게 아니라 스스로 인식해서 행동하는 인공지능인 것 같다고 생각했는데 사양서를 잘 보면 쇼통신호의 상태에 따라서 로봇의 보행속도를 결정한다고 써 있기 때문에 스스로가 아니라 다른 곳에서 명랑을 받고 행동할 가능성도 생각했습니다. 로봇이 보행속도를 결정한다고 써 있으면 "RobtWalk에서 스캐너를 반복적으로 진행"하는 것이 좋을 것 같지만, 좀 다시 같이 고민할 필요가 있다고 생각합니다.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yuikateraoka** [comment]
네 감사합니다.

질문 내용:
1. 로봇이 인공지능인지 
2. 최고 속도에 대해
3. 교통신호 노란색일 경우에서 1.2를 곱하게 되면 speed가 float or double이 되는대 이 문제에 대해

일단 이런 질문 3가지를 정리했는데 추가사항이 있으면 공유 부탁드리겠습니다.

**Comment by yuikateraoka** [comment]
요구사양에 없는 추가적인 것은 어떤 식으로 해도 괜찮을  수도 있는데 반대로 상양대로 기본적인 요구만 채우고 필요없는 것은 추가 안 하고 simple하게 하는게 좋지 않을까 싶습니다. 
아이디어가 많다면 몇게나 생길 수 있는 case를 작성해도 괜찮을 것 같은데 어떻습니까?

**Comment by KimJinsu66** [comment]
좋네요 Windows 10용 메일에서 보냄 보낸 사람: yuikateraoka보낸 날짜: 2020년 4월 6일 월요일 오후 2:39받는 사람: KimJinsu66/TeamProject-2참조: KimJinsu66; Author제목: Re: [KimJinsu66/TeamProject-2] RobotWalk Scanner (#1) 요구사양에 없는 추가적인 것은 어떤 식으로 해도 괜찮을 수도 있는데 반대로 상양대로 기본적인 요구만 채우고 필요없는 것은 추가 안 하고 simple하게 하는게 좋지 않을까 싶습니다.아이디어가 많다면 몇게나 생길 수 있는 case를 작성해도 괜찮을 것 같은데 어떻습니까?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by KimJinsu66** [comment]
우선 simple하게 가는게 좋을 것 같네요. 위에 질문 3가지에 대해서만 우선적으로 해결하고 statement coverage로 넘어가면 될꺼같아요 .

**Comment by yuikateraoka** [comment]
네 그럼 수요일에 여쭤보고 피드백 받은 후 결정합시다.
수요일까지는 signature를 좀 정리해놓시다.
저의 생각은 아래와 같습니다.

①signature  of Speed Class
   method name(함수이름) > RobotWalk
   parameter(매개변수) > speed , trafficLight<String>
   return type(반환값,리턴값) > speed


②signature of Speed1 Class
   method name(함수이름) > RobotWalk
   parameter(매개변수) > speed , sc
   return type(반환값,리턴값) >  speed

**Comment by yuikateraoka** [comment]
signature of Speed Class
method name(함수이름) > RobotWalk
parameter(매개변수) > speed 
return type(반환값,리턴값) > speed
